### PR TITLE
adds support for @custom-selector

### PR DESCRIPTION
**Pull request by shanewilson**
Thanks for making this - really simplifies using postcss.

### CODE REVIEW

**Comment by aaronj1335** [comment]
awesome, i'll take a look at this when i've got some time here. if you could add unit tests that'd be a big help and would speed things along!

**Comment by shanewilson** [comment]
I may have gone over board here - I'm not really a node developer so I just copied from here: https://github.com/postcss/postcss-loader

**Comment by aaronj1335** [comment]
naw this is actually great, i really like the eslint addition, the tests look good, and you've got the correct approach. unfortunately i don't want to add a dependency on gulp, but i think that will be easy to rework. there's also a few nits, but i want to give you a proper review here when i've got a few more minutes, so maybe later today or tomorrow.

**Comment by aaronj1335** [comment]
ugh had path issues on the travis CI builds, so this was actually closed in 2c42967.

thanks so much for the contribution! i've published it to npm v1.1.0.

**Pull request merged**
